import Head from "next/head";

import ContactUsSection from "@/components/landing-page/contact-us-section/contact-us-section";


export default function Index() {
  return (
    <>
      <Head>
        <title>hyring-contact-us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactUsSection/>
        
     
    </>
  );
}
