import Head from "next/head";
import HomeBannerSection from "@/components/landing-page/home-banner-section/home-banner-section";
import PricingSection from "@/components/landing-page/pricing-section/pricing-section";
import TalentSection from "@/components/landing-page/talents-section/talents-section";
import { useScroll, useTransform, motion } from "framer-motion";
import ScrollIcon from "@/assets/icons/landing-page/scroll_icon";
import PromiseSection from "@/components/landing-page/promises-section/promises-section";
import NavbarComponent from "@/common/landing-page/navbar/navbar-component";
import Footer from "@/common/landing-page/footer/footer";
import Image from "next/image";
import { useRef } from "react";
import CarouselSection3 from "@/components/landing-page/carousel-section/carousel-section3";
import CarouselSection2 from "@/components/landing-page/carousel-section/carousel-section2";
import CarouselSection1 from "@/components/landing-page/carousel-section/carousel-section1";

export default function Home() {
  let ref = useRef(null);
  const { scrollY } = useScroll();
  const y = useTransform(scrollY, [0, 4800], [0, 154]);
  const rotate = useTransform(scrollY, [0, 4800], [-1080, 0]);
  let { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start start", "end start"],
  });

  let yAxis = useTransform(scrollYProgress, [0, 1], ["0%", "50%"]);
  let scale = useTransform(scrollYProgress, [0, 1], ["99.9%", "100%"]);
  let opacity = useTransform(scrollYProgress, [0.98, 1], [1, 0.98]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative text-primary-brown" ref={ref}>
        <div className="invisible lg:visible fixed right-2 top-[50%] scale-[0.6] sm:scale-[0.7] md:scale-[0.8] lg:scale-[1] translate-x-1 md:translate-x-0 -translate-y-1/2 bg-[#FFF7EF] h-44 w-7 rounded-xl border-primary-brown border z-30">
          <motion.div
            className="flex justify-center"
            animate={{
              rotate: [0, 360],
              borderRadius: ["0%", "0%", "50%", "50%", "0%"],
            }}
            transition={{
              duration: 0,
              ease: "easeInOut",
              repeat: Infinity,
              repeatDelay: 0,
            }}
            style={{
              rotate,
              y,
              transition: "transform 0.1s ease-out",
            }}
          >
            <ScrollIcon />
          </motion.div>
        </div>
        <motion.div style={{ yAxis, scale, opacity }}>
          <Image
            src="/Rectangle.svg"
            fill
            style={{ objectFit: "cover", zIndex: -10 }}
            alt="Background-Image"
            quality={100}
            priority
          />
          <NavbarComponent />

          <div
            data-aos="fade-up"
            data-aos-duration="500"
            data-aos-easing="linear"
          >
            <HomeBannerSection />
          </div>
          <div
            data-aos="fade-up"
            data-aos-duration="600"
            data-aos-easing="linear"
          >
            <PromiseSection />
          </div>
          <div
            data-aos="fade-up"
            data-aos-duration="600"
            data-aos-easing="linear"
          >
            <TalentSection />
          </div>
          <div>
            <div
              // data-aos="fade-up"
              // data-aos-duration="100"
              // data-aos-easing="linear"
              className="sticky top-0 "
            >
              <CarouselSection1 />
            </div>
            <div
              // data-aos="fade-up"
              // data-aos-duration="600"
              // data-aos-easing="linear"
              className="sticky top-4 px-2"
            >
              <CarouselSection2 />
            </div>
            <div
              // data-aos="fade-up"
              // data-aos-duration="600"
              // data-aos-easing="linear"
              className="sticky top-8 px-4"
            >
              <CarouselSection3 />
            </div>
          </div>
          <PricingSection />
          <Footer />
        </motion.div>
      </div>
    </>
  );
}
